### ISSUE TITLE
Bounty for documenting notes EIPIP Meeting 107

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/PM#408]
## Document notes for EIPIP meeting 107

- Bounty - 100 DAI
- Agenda - https://github.com/ethcatherders/EIPIP/issues/346
- [Video](https://youtu.be/DgdzaxHWFcA)
- Guidelines & template - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md
- Create a Pull Request to submit the notes [here](https://github.com/ethcatherders/EIPIP/pulls)

### Submission timeline - July 21, 12:00 pm EST

Respond to this issue if you would like to work on this task.

### Note: If you are a first-time contributor, please share your notes in a hackmd.io file for review before making the Pull Request.

**Comment by Emmanueltech** [comment]
Hi, I would like to work on this task.

**Comment by poojaranjan** [comment]
Hi @Emmanueltech, could you please pick one of the two tasks? So we can provide the opportunities to other contributors as well.

**Comment by AbuTuraab** [comment]
Hi @poojaranjan , this issue, right?

**Comment by poojaranjan** [comment]
@AbuTuraab, 
Yes. Assigned to you. Please be mindful of the submission timeline and format.

**Comment by AbuTuraab** [comment]
Noted, @poojaranjan thank you.

**Comment by shubha-me** [comment]
Interested

**Comment by AbuTuraab** [comment]
Hi @poojaranjan Hope you are doing great, here is a draft of  the meeting notes I was assigned, kindly check and give me your feedbacks.

https://hackmd.io/@CwZlNOPxTxSfBjX1jf0NkA/SyV1vdY_A

regards

**Comment by poojaranjan** [comment]
Thanks for sharing. The format looks good. 

Please 
- update "ETHEREUM CAT HEADERS EIPIP MEETING #107" to "EIPIP Meeting 107"
- Add 
# 1. Discuss Open Issues/PRs, and other topics
## Edit to Final Proposals
#### https://github.com/ethereum/ERCs/pull/403
before **Pooja** [0:00](https://www.youtube.com/watch?v=DgdzaxHWFcA&t=0s) and everywhere before the topic starts.
- bold name of speakers like **Sam**
- add hyperlink to time stamp like "1:18" as "https://www.youtube.com/watch?v=DgdzaxHWFcA&t=78s"
- Please update [Readme](https://github.com/ethcatherders/EIPIP/blob/master/README.md) file and add that to your Pull Request.

**Comment by AbuTuraab** [comment]
Hi @poojaranjan kindly check, I have ceated a pull request,

Regards.

**Comment by poojaranjan** [comment]
@AbuTuraab
Thanks for making the PR.  Please check the comments to update the Pull Request asap.

**Comment by AbuTuraab** [comment]
Done that.

**Comment by AbuTuraab** [comment]
@poojaranjan done.

**Comment by AbuTuraab** [comment]
Hi @poojaranjan have you been able to check please?

**Comment by poojaranjan** [comment]
@AbuTuraab 
notes aren't ready to be merged. Please make the changes suggested on the Pull Request.

**Comment by AbuTuraab** [comment]
Ohh, my bad, I thought i did that earlier, please check now, i have pushed the changes @poojaranjan

**Comment by AbuTuraab** [comment]
Hi @poojaranjan how are you doing, I'm not sure if you got my earlier notification on the changes made to the notes, kindly check for confirmation.

Regards.

**Comment by zkdoof** [comment]
> Hi @poojaranjan how are you doing, I'm not sure if you got my earlier notification on the changes made to the notes, kindly check for confirmation.

Hi @AbuTuraab I can confirm you've completed the bounty. 

Can you please leave your email or discord handle so I can reach out to you to start the payment process?

**Comment by AbuTuraab** [comment]
Hi @zkdoof  thank you for reaching out, I hope everything is okay with @poojaranjan , I have been worried i didnt get any response from her for a while now.

my discord is @abu_turaab and my email is aliyulekan@gmail.com

Thanks

**Comment by Aleneth** [comment]
Closing in favor of https://github.com/ethcatherders/funding/issues/657
