### ISSUE TITLE
Bounty for documenting notes ACDE Meeting 192

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/PM#409]
## Document notes for ACDE Meeting 192

- [Video](https://youtube.com/live/kL58hvM0E68)
- Bounty - 150 DAI
- Agenda - https://github.com/ethereum/pm/issues/1098
- Guidelines & template - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md
- Create a Pull Request to submit the notes [here](https://github.com/ethereum/pm/pulls)

### Submission timeline - July 21, 12:00 pm EST

Respond to this issue if you would like to work on this task.

### Note: If you are a first-time contributor, please share your notes in a hackmd.io file for review before making the Pull Request.

**Comment by Emmanueltech** [comment]
Hi, I would like to work on this task.

**Comment by poojaranjan** [comment]
Hi @Emmanueltech, could you please pick one of the two tasks? So we can provide the opportunities to other contributors as well.

**Comment by Emmanueltech** [comment]
understood, this one.

**Comment by AbuTuraab** [comment]
Hi @poojaranjan can I take on this task, I will be glad to contribute to the community.

**Comment by poojaranjan** [comment]
@Emmanueltech Since you responded first, you may work on the task, please be mindful of the timeline and format of notes submission.

**Comment by poojaranjan** [comment]
@AbuTuraab would you want to take the other open Issue?

**Comment by AbuTuraab** [comment]
Yeah, @poojaranjan let me take the other open issue.

**Comment by Emmanueltech** [comment]
@poojaranjan Noted, thank you.

**Comment by SaintVilliern** [comment]
Hi @poojaranjan can I take on the tasks too since its a bounty with a deadline. I will be glad to contribute to the community and if the others submit before me, at least I would learn how to do the documentation and prepare myself for the next meeting. Please let me know your thoughts on this suggestion. Thank you

**Comment by Emmanueltech** [comment]
@poojaranjan I've completed the transcriptions and just need to transfer them to Markdown and submit a pull request. Would it be okay if I submit it 5-7 hours past the deadline? The document is about 23 pages long, and I’m also adding YouTube timestamps. You can review the current work here: [Google Doc Link](https://docs.google.com/document/d/1PdL0PnK9OdZ3THcFmTjrccgpoYd-hYAJLzQqTXXFb4w/edit?usp=sharing).

**Comment by poojaranjan** [comment]
@Emmanueltech 
Taking a quick look at the google docs, a few recommendations for notes.
- Please follow the template to make the notes looks like [this](/https://github.com/ethereum/pm/blob/master/AllCoreDevs-EL-Meetings/Meeting%20187.md).
- use name (Tim Beiko) instead of adding "moderator"
- add agenda topics as listed on the agenda with proper #s 
- add zoom chat at the end of the notes 
[ACDE Chat 193.txt](https://github.com/user-attachments/files/16325770/ACDE.Chat.193.txt)
- update [Readme](https://github.com/ethereum/pm/blob/master/README.md#previous-allcoredevs-meetings) and add with the PR

Please make the changes and submit the Pull Request by 9:00 am EST.

**Comment by Emmanueltech** [comment]
Understood. The first link you added is broken, please check. Here is how the transfer looks on hackmd https://hackmd.io/@emmanueleclipse/SJLmfG5dA

I'm going to make the other changes as soon as I'm done moving the text to hackmd

**Comment by poojaranjan** [comment]
> Understood. The first link you added is broken, please check. 
Fixed, pls revisit. 

> I'm going to make the other changes as soon as I'm done moving the text to hackmd
Sure.

**Comment by poojaranjan** [comment]
Please update the header and formatting as per agenda item 

<img width="441" alt="Screenshot 2024-07-21 at 3 22 49 PM" src="https://github.com/user-attachments/assets/f0e57587-4c42-456e-a228-932f5bce7f25">

Instead of 
<img width="768" alt="Screenshot 2024-07-21 at 3 23 34 PM" src="https://github.com/user-attachments/assets/1cf03d42-84a9-4904-80c5-701dfb08b8f0">

Please change to 
# Pectra
## [devnet-1](https://notes.ethereum.org/@ethpandaops/pectra-devnet-1) updates
(notes)
## [EOF concerns](https://mariusvanderwijden.github.io/blog/2024/07/12/EOF/)
(notes)

Let me know in case of any questions.

**Comment by Emmanueltech** [comment]
Understood. Thanks

**Comment by Emmanueltech** [comment]
@poojaranjan Please check and provide feedback before I continue, also the last agenda (EIP-4444 Updates) was not discussed do I add it in the agenda and summary as (Not discussed)?

**Comment by Emmanueltech** [comment]
Sent a pull request

**Comment by poojaranjan** [comment]
It seems the PR is missing the Notes file. Please add.

**Comment by Emmanueltech** [comment]
@poojaranjan Should be there now, please check.

**Comment by poojaranjan** [comment]
Looks, good. Just suggested some changes to README. Kindly, accept. Thanks.

**Comment by Emmanueltech** [comment]
@poojaranjan Done

**Comment by poojaranjan** [comment]
@Emmanueltech please DM me on ECH Discord to inform you about the Bounty claim process.

**Comment by Emmanueltech** [comment]
@poojaranjan Understood. My discord is emmanueleclipse_ I will Dm you now

**Comment by Aleneth** [comment]
Closing in favor of https://github.com/ethcatherders/funding/issues/656
